apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: minecraft
  chart:
    spec:
      chart: ./minecraft/charts/minecraft
  values:
    image:
      repository: itzg/minecraft-server
      tag: latest
    minecraftServer:
      name: eula
      value: true
